import type { KPRule } from '../types';

export const cuspalSubLords: KPRule[] = [
  // ── 1st House ──────────────────────────────────────────────────────────────
  {
    id: 'csl-01',
    section: 'cuspal-sublords',
    subsection: '1st-house',
    houses: [1],
    rule: 'The 1st cusp sub-lord is the primary indicator of physical constitution, longevity, and the overall quality of the native\'s life. It defines the lens through which all other houses express themselves.',
  },
  {
    id: 'csl-02',
    section: 'cuspal-sublords',
    subsection: '1st-house',
    houses: [1, 5, 9],
    rule: 'If the 1st cusp sub-lord signifies houses 1, 5, or 9 (trikona houses) without strong 6/8/12 influence, the native enjoys robust physical health, good vitality, and a generally fortunate life pattern.',
  },
  {
    id: 'csl-03',
    section: 'cuspal-sublords',
    subsection: '1st-house',
    houses: [1, 6, 8, 12],
    rule: 'If the 1st cusp sub-lord primarily signifies house 6, the native is prone to illness but recovers; the house 6 connection also indicates a life involving service to others. Signifying house 8 suggests chronic or serious health conditions and transformative life events. Signifying house 12 points to hospitalization risk, mental health sensitivity, or confinement-related themes at key life periods.',
  },
  // ── 2nd House ──────────────────────────────────────────────────────────────
  {
    id: 'csl-04',
    section: 'cuspal-sublords',
    subsection: '2nd-house',
    houses: [2],
    rule: 'The 2nd cusp sub-lord determines the native\'s capacity to accumulate wealth, the harmony of family life, and the quality of speech. It is also a secondary indicator of longevity (2nd is a maraka house — if afflicted, it shortens life).',
  },
  {
    id: 'csl-05',
    section: 'cuspal-sublords',
    subsection: '2nd-house',
    houses: [2, 10, 11],
    rule: 'If the 2nd cusp sub-lord signifies houses 2, 10, and 11, steady and growing financial accumulation is strongly promised — earned through profession and fulfilled desires.',
  },
  {
    id: 'csl-06',
    section: 'cuspal-sublords',
    subsection: '2nd-house',
    houses: [2, 6, 8, 12],
    rule: 'If the 2nd cusp sub-lord predominantly signifies houses 6, 8, or 12, the native earns but struggles to save or accumulate: house 6 = expenses through debts; house 8 = sudden financial disruptions; house 12 = money flows out as fast as it comes in.',
  },
  // ── 3rd House ──────────────────────────────────────────────────────────────
  {
    id: 'csl-07',
    section: 'cuspal-sublords',
    subsection: '3rd-house',
    houses: [3],
    rule: 'The 3rd cusp sub-lord indicates siblings, short journeys, communication ability, writing, and courage. If it signifies house 3 and has connections to 9, the native is a natural communicator and may write or speak publicly.',
  },
  {
    id: 'csl-08',
    section: 'cuspal-sublords',
    subsection: '3rd-house',
    houses: [3, 6, 8],
    rule: 'If the 3rd cusp sub-lord signifies house 6 or 8, relations with siblings may be difficult or characterized by competition and conflict. House 12 connection can indicate separation from siblings.',
  },
  // ── 4th House ──────────────────────────────────────────────────────────────
  {
    id: 'csl-09',
    section: 'cuspal-sublords',
    subsection: '4th-house',
    houses: [4],
    rule: 'The 4th cusp sub-lord determines property ownership, domestic happiness, relationship with mother, and educational foundation. It is also a key indicator of the native\'s sense of inner peace and stability.',
  },
  {
    id: 'csl-10',
    section: 'cuspal-sublords',
    subsection: '4th-house',
    houses: [4, 11, 12],
    rule: 'If the 4th cusp sub-lord signifies houses 4, 11, and 12, property acquisition is strongly indicated. The house 12 connection represents expenditure made for the purchase (investing savings into property), and house 11 confirms the fulfillment of this desire.',
  },
  {
    id: 'csl-11',
    section: 'cuspal-sublords',
    subsection: '4th-house',
    houses: [4, 6, 8],
    rule: 'If the 4th cusp sub-lord primarily signifies houses 6 or 8, domestic life is troubled: house 6 indicates frequent disputes at home; house 8 suggests transformation of domestic life through significant upheaval.',
  },
  // ── 5th House ──────────────────────────────────────────────────────────────
  {
    id: 'csl-12',
    section: 'cuspal-sublords',
    subsection: '5th-house',
    houses: [5],
    rule: 'The 5th cusp sub-lord governs progeny (children), romance, speculation, higher education, and creative self-expression. It is also a spiritual indicator — the 5th house is a dharma house.',
  },
  {
    id: 'csl-13',
    section: 'cuspal-sublords',
    subsection: '5th-house',
    houses: [5, 2, 11],
    rule: 'For childbirth promise: the 5th cusp sub-lord must signify houses 2 (family expansion), 5 (children), and 11 (fulfillment of desire) to confirm that children are promised in the chart.',
  },
  {
    id: 'csl-14',
    section: 'cuspal-sublords',
    subsection: '5th-house',
    houses: [5, 8, 12],
    rule: 'If the 5th cusp sub-lord signifies houses 5 and 8 or 12 predominantly for speculation, investment losses are likely. The speculative impulse exists (5th house) but the outcome is loss (8th = sudden reversal; 12th = drain).',
  },
  {
    id: 'csl-15',
    section: 'cuspal-sublords',
    subsection: '5th-house',
    houses: [5, 1, 4, 10],
    rule: 'If the 5th cusp sub-lord signifies houses 1, 4, or 10 with 5, educational achievement and intellectual distinction are indicated. The native\'s creative or intellectual output becomes part of their public identity.',
  },
  // ── 6th House ──────────────────────────────────────────────────────────────
  {
    id: 'csl-16',
    section: 'cuspal-sublords',
    subsection: '6th-house',
    houses: [6],
    rule: 'In KP, house 6 is the house of service and employment (positive for salaried professionals), illness and enemies (when afflicted), and competition. The 6th cusp sub-lord determines whether service will be the native\'s primary career mode.',
  },
  {
    id: 'csl-17',
    section: 'cuspal-sublords',
    subsection: '6th-house',
    houses: [6, 10, 11],
    rule: 'If the 6th cusp sub-lord signifies houses 6, 10, and 11, a career in employment (salaried service) is strongly promised with recognition and financial gains from that service.',
  },
  {
    id: 'csl-18',
    section: 'cuspal-sublords',
    subsection: '6th-house',
    houses: [6, 1, 8, 12],
    rule: 'If the 6th cusp sub-lord primarily signifies houses 1, 8, or 12 rather than 10 and 11, the native may face chronic health issues, legal troubles, or problems with enemies that overshadow the employment dimension of this house.',
  },
  // ── 7th House ──────────────────────────────────────────────────────────────
  {
    id: 'csl-19',
    section: 'cuspal-sublords',
    subsection: '7th-house',
    houses: [7],
    rule: 'The 7th cusp sub-lord is the single most important determinant of marriage and committed partnership in KP. Its significations either promise or deny marriage, independent of how many favorable planets are in the 7th house.',
  },
  {
    id: 'csl-20',
    section: 'cuspal-sublords',
    subsection: '7th-house',
    houses: [2, 7, 11],
    rule: 'Marriage is promised if the 7th cusp sub-lord signifies at least two of: house 2 (family formation), house 7 (partnership), and house 11 (fulfillment of desire for a companion). Ideally all three are signified.',
  },
  {
    id: 'csl-21',
    section: 'cuspal-sublords',
    subsection: '7th-house',
    houses: [7, 6, 10],
    rule: 'If the 7th cusp sub-lord signifies houses 1, 6, or 10 without adequate 2/7/11 connection, marriage is delayed, the native prioritizes career or self over partnership, or the commitment is avoided.',
  },
  {
    id: 'csl-22',
    section: 'cuspal-sublords',
    subsection: '7th-house',
    houses: [7, 6, 8, 12],
    rule: 'If the 7th cusp sub-lord predominantly signifies houses 6, 8, and 12 together, serious marital difficulties are indicated: house 6 = conflict and ill health in spouse; house 8 = sudden upheaval or spouse\'s death; house 12 = foreign partner or eventual separation/bed-separation.',
  },
  {
    id: 'csl-23',
    section: 'cuspal-sublords',
    subsection: '7th-house',
    houses: [7, 12],
    rule: 'If the 7th cusp sub-lord signifies house 12 alongside 2/7/11, the partnership has a foreign, spiritual, or reclusive quality. The spouse may be foreign-born, or the marriage involves living abroad.',
  },
  // ── 8th House ──────────────────────────────────────────────────────────────
  {
    id: 'csl-24',
    section: 'cuspal-sublords',
    subsection: '8th-house',
    houses: [8],
    rule: 'The 8th cusp sub-lord is the primary indicator of longevity, legacy inheritance, occult interests, and transformative life events. It also governs insurance benefits, partner\'s wealth, and sudden changes.',
  },
  {
    id: 'csl-25',
    section: 'cuspal-sublords',
    subsection: '8th-house',
    houses: [1, 3, 8],
    rule: 'Longevity is well-supported when the 8th cusp sub-lord primarily signifies houses 1 and 3 (both are life-affirming trine and upachaya connections). House 3 is the 8th from the 8th — it protects longevity.',
  },
  {
    id: 'csl-26',
    section: 'cuspal-sublords',
    subsection: '8th-house',
    houses: [2, 7, 8],
    rule: 'Shortened longevity risk when the 8th cusp sub-lord predominantly signifies houses 2 and 7 — these are the maraka (death-inflicting) houses. This does not predict early death but marks a life where health and vitality require more consistent care.',
  },
  // ── 9th House ──────────────────────────────────────────────────────────────
  {
    id: 'csl-27',
    section: 'cuspal-sublords',
    subsection: '9th-house',
    houses: [9],
    rule: 'The 9th cusp sub-lord governs higher education, fortune, father, dharma, long journeys, and spiritual inclination. It is the house of past-life merit and indicates the general fortune of the chart.',
  },
  {
    id: 'csl-28',
    section: 'cuspal-sublords',
    subsection: '9th-house',
    houses: [9, 12],
    rule: 'If the 9th cusp sub-lord signifies houses 9 and 12 together, the native is inclined toward long-distance travel, foreign settlement, or spiritual retreat. The conjunction of fortune (9) and withdrawal/foreign lands (12) creates a nomadic or internationally-connected life.',
  },
  {
    id: 'csl-29',
    section: 'cuspal-sublords',
    subsection: '9th-house',
    houses: [9, 3],
    rule: 'If the 9th cusp sub-lord signifies houses 3 and 9, the native is a natural teacher, writer, or traveler — the axis of communication and higher knowledge is strongly activated.',
  },
  // ── 10th House ─────────────────────────────────────────────────────────────
  {
    id: 'csl-30',
    section: 'cuspal-sublords',
    subsection: '10th-house',
    houses: [10],
    rule: 'The 10th cusp sub-lord is the primary determinant of career, public status, and professional achievement. Its house significations reveal whether the native will succeed in employment, business, creative arts, authority, or service.',
  },
  {
    id: 'csl-31',
    section: 'cuspal-sublords',
    subsection: '10th-house',
    houses: [6, 10, 11],
    rule: 'A career in employment (salaried service) with recognition is promised when the 10th cusp sub-lord signifies houses 6, 10, and 11. The career rises steadily with gains (11) from professional effort (10) within a service structure (6).',
  },
  {
    id: 'csl-32',
    section: 'cuspal-sublords',
    subsection: '10th-house',
    houses: [2, 7, 10, 11],
    rule: 'A business or entrepreneurial career is indicated when the 10th cusp sub-lord signifies houses 2 (accumulation), 7 (partnerships and deals), and 10 (action). The house 11 signification adds profit from business dealings.',
  },
  {
    id: 'csl-33',
    section: 'cuspal-sublords',
    subsection: '10th-house',
    houses: [10, 12],
    rule: 'If the 10th cusp sub-lord signifies house 12 along with 10, the career may involve foreign companies, remote work, behind-the-scenes operations, research, or spiritual/healing professions.',
  },
  {
    id: 'csl-34',
    section: 'cuspal-sublords',
    subsection: '10th-house',
    houses: [1, 4, 10],
    rule: 'If the 10th cusp sub-lord primarily signifies houses 1 and 4 without strong 6/10/11 connections, career advancement is slow or the native prefers private life to public recognition. The professional ambition is directed inward rather than outward.',
  },
  // ── 11th House ─────────────────────────────────────────────────────────────
  {
    id: 'csl-35',
    section: 'cuspal-sublords',
    subsection: '11th-house',
    houses: [11],
    rule: 'The 11th cusp sub-lord determines the fulfillment of desires, income beyond regular salary, social networks, and elder siblings. It is the most critical house for financial gains.',
  },
  {
    id: 'csl-36',
    section: 'cuspal-sublords',
    subsection: '11th-house',
    houses: [2, 10, 11],
    rule: 'If the 11th cusp sub-lord signifies houses 2, 10, and 11, steady and growing financial gains from professional effort are strongly promised. The native builds wealth methodically through career.',
  },
  {
    id: 'csl-37',
    section: 'cuspal-sublords',
    subsection: '11th-house',
    houses: [6, 8, 11, 12],
    rule: 'If the 11th cusp sub-lord primarily signifies houses 6, 8, or 12 without 2/10/11, desires are frequently frustrated: house 6 = income comes through struggle and debt repayment; house 8 = gains blocked by sudden losses; house 12 = earnings dissipated in expenditure.',
  },
  // ── 12th House ─────────────────────────────────────────────────────────────
  {
    id: 'csl-38',
    section: 'cuspal-sublords',
    subsection: '12th-house',
    houses: [12],
    rule: 'The 12th cusp sub-lord governs expenditure, losses, foreign residence, spiritual withdrawal, hospitalization, and liberation (moksha). It indicates what drains the native\'s resources — and also what liberates them.',
  },
  {
    id: 'csl-39',
    section: 'cuspal-sublords',
    subsection: '12th-house',
    houses: [3, 9, 12],
    rule: 'If the 12th cusp sub-lord signifies houses 3, 9, and 12, foreign settlement or long-term residence abroad is strongly indicated. The axis of travel (3 = short journeys, 9 = long journeys) connected to 12 (foreign lands) creates the emigration pattern.',
  },
  {
    id: 'csl-40',
    section: 'cuspal-sublords',
    subsection: '12th-house',
    houses: [2, 12],
    rule: 'If the 12th cusp sub-lord signifies houses 2 and 12, expenditure is heavy but the native generally earns enough to sustain it. A pattern of spending on family, luxuries, or status is common.',
  },
];
