import type { KPRule } from '../types';

export const marriage: KPRule[] = [
  {
    id: 'mar-01',
    section: 'marriage',
    houses: [2, 7, 11],
    rule: 'Marriage is fundamentally promised in KP when the 7th cusp sub-lord signifies at least two of the three marriage houses: 2 (family formation), 7 (direct partnership), and 11 (fulfillment of desire for a companion). All three together indicate near-certain marriage.',
  },
  {
    id: 'mar-02',
    section: 'marriage',
    houses: [7],
    rule: 'The 7th cusp sub-lord is the final authority on marriage. Even if Venus (karaka for marriage) is well-placed in the 7th house, if the cusp sub-lord\'s significations do not support marriage houses, the event will not materialize in full.',
  },
  {
    id: 'mar-03',
    section: 'marriage',
    houses: [7, 6, 8, 12],
    rule: 'If the 7th cusp sub-lord signifies houses 2, 7, 11 but also connects to houses 6, 8, or 12, marriage occurs but with modifications: house 6 = spouse faces health issues or marital conflict is persistent; house 8 = sudden transformation of the relationship; house 12 = bed-pleasures are present but practical separation may occur later in life.',
  },
  {
    id: 'mar-04',
    section: 'marriage',
    keywords: ['manglik', 'dosha'],
    rule: 'Manglik Dosha in KP is assessed by whether Mars, as a significator, connects houses 1, 2, 4, 7, 8, or 12 through its cuspal sub-lord positions — not merely by Mars\'s house placement as in traditional Vedic. The dosha is confirmed only if Mars\'s actual significations harm the 7th cusp sub-lord\'s promise.',
  },
  {
    id: 'mar-05',
    section: 'marriage',
    keywords: ['manglik', 'cancellation'],
    rule: 'In KP analysis, if both partners have Mars as a significator of the same difficult houses (double Manglik), the dosha effectively cancels for the marriage between them — their shared energy pattern becomes a source of compatibility rather than conflict.',
  },
  {
    id: 'mar-06',
    section: 'marriage',
    planets: ['Venus'],
    rule: 'Venus is the karaka (natural significator) for marriage for all charts. If Venus is a significator of houses 2, 7, or 11 in the KP signification cascade, it strongly supports the marriage promise. If Venus primarily signifies 6, 8, or 12, love relationships face disruption even if they form.',
  },
  {
    id: 'mar-07',
    section: 'marriage',
    planets: ['Jupiter'],
    rule: 'In female charts, Jupiter is the karaka for the husband. If Jupiter signifies houses 2, 7, and 11 in KP analysis, the husband will be a positive, expansive presence in the native\'s life. If Jupiter signifies 6 or 8, the husband may face health issues or bring transformation through crisis.',
  },
  {
    id: 'mar-08',
    section: 'marriage',
    houses: [7, 12],
    rule: 'If the 7th cusp sub-lord is in the constellation of a planet primarily placed in house 12, the partner is likely foreign-born, met during travel, or the relationship involves residence in a foreign country.',
  },
  {
    id: 'mar-09',
    section: 'marriage',
    houses: [1, 3, 7],
    rule: 'Multiple partnerships are indicated when the 7th cusp sub-lord signifies house 1 or 3 alongside 7, and there are additional planets signifying houses 2 and 11. The native is likely to have more than one significant committed relationship in their life.',
  },
  {
    id: 'mar-10',
    section: 'marriage',
    keywords: ['timing', 'dasha'],
    rule: 'The dasha period that brings marriage must have: the Mahadasha lord as a significator of houses 2, 7, or 11; the Antardasha lord also as a significator of 2, 7, or 11; and the Pratyantar lord confirming. Even one non-aligned level delays the event to the next sub-period.',
  },
  {
    id: 'mar-11',
    section: 'marriage',
    planets: ['Jupiter'],
    keywords: ['timing', 'transit'],
    rule: 'For marriage timing, Jupiter\'s transit over the natal 7th cusp degree, the natal position of the 7th cusp sub-lord, or the natal 7th house lord confirms the marriage year. This transit confirmation is almost always present in the year of marriage.',
  },
  {
    id: 'mar-12',
    section: 'marriage',
    planets: ['Saturn'],
    houses: [7],
    rule: 'If Saturn is the sub-lord of the 7th cusp, marriage is delayed — typically occurring in the late 20s or 30s, or in a Saturn dasha/antardasha period. Once it occurs, the marriage tends to be stable, practical, and long-lasting.',
  },
  {
    id: 'mar-13',
    section: 'marriage',
    planets: ['Rahu'],
    houses: [7],
    rule: 'If Rahu is the sub-lord of the 7th cusp, the marriage has an unconventional quality: the spouse may be from a different caste, religion, culture, or nationality. Inter-community or cross-cultural marriages are strongly indicated.',
  },
  {
    id: 'mar-14',
    section: 'marriage',
    planets: ['Moon'],
    houses: [7],
    rule: 'If the Moon is the sub-lord of the 7th cusp, the native is emotionally driven in love and typically marries someone they have known intimately for a significant period. The marriage has strong emotional depth and the partner plays a nurturing or protective role.',
  },
  {
    id: 'mar-15',
    section: 'marriage',
    planets: ['Mars'],
    houses: [7],
    rule: 'If Mars is the sub-lord of the 7th cusp, the partner is dynamic, energetic, and possibly aggressive or dominating. The relationship has passion but also conflict potential. The native is attracted to decisive, driven partners.',
  },
  {
    id: 'mar-16',
    section: 'marriage',
    planets: ['Mercury'],
    houses: [7],
    rule: 'If Mercury is the sub-lord of the 7th cusp, the native values intellectual compatibility above all in a partner. The spouse is typically educated, communicative, and clever. Shared ideas and mental stimulation define the marriage.',
  },
  {
    id: 'mar-17',
    section: 'marriage',
    planets: ['Ketu'],
    houses: [7],
    rule: 'If Ketu is the sub-lord of the 7th cusp, the marriage has a karmic quality — the partner may feel like a soul known from a past life. The relationship may be spiritually deep but practically unconventional or marked by sudden separation.',
  },
  {
    id: 'mar-18',
    section: 'marriage',
    houses: [5, 7, 11],
    rule: 'A love marriage (as opposed to arranged) is more likely when the 5th cusp sub-lord also signifies houses 7 and 11, connecting romance (5th house) directly to the partner (7th) and fulfillment (11th).',
  },
  {
    id: 'mar-19',
    section: 'marriage',
    houses: [7, 8],
    keywords: ['widowhood', 'separation'],
    rule: 'The risk of early widowhood or permanent separation is indicated when the 7th cusp sub-lord predominantly signifies houses 6, 8, and 12 together — the combination of conflict (6), sudden ending (8), and isolation (12) around the 7th house matter.',
  },
  {
    id: 'mar-20',
    section: 'marriage',
    keywords: ['timing', 'transit', 'double-transit'],
    rule: 'The double-transit rule for marriage: both Jupiter and Saturn must simultaneously transit signs that support the natal Moon and the 7th cusp\'s sub-lord position for a marriage year to fully activate. One planet alone is not sufficient for major relationship milestones.',
  },
];
