import type { KPRule } from '../types';

export const career: KPRule[] = [
  {
    id: 'car-01',
    section: 'career',
    houses: [10],
    rule: 'The 10th cusp sub-lord is the primary authority on career mode in KP. Its house significations determine whether the native succeeds in employment, business, creative work, authority, or a vocation of service.',
  },
  {
    id: 'car-02',
    section: 'career',
    houses: [6, 10, 11],
    rule: 'A career in salaried employment with steady recognition is promised when the 10th cusp sub-lord signifies houses 6 (service), 10 (professional action), and 11 (gains). The 6th house is positive for employed professionals in KP — it is the house of service, not just illness.',
  },
  {
    id: 'car-03',
    section: 'career',
    houses: [2, 7, 10, 11],
    rule: 'A business or entrepreneurial career is indicated when the 10th cusp sub-lord signifies houses 2 (accumulation), 7 (partnerships, deals, clients), and 10 (independent professional action). House 11 adds the profit dimension to business dealings.',
  },
  {
    id: 'car-04',
    section: 'career',
    planets: ['Saturn'],
    houses: [10],
    rule: 'If Saturn is the sub-lord or star lord of the 10th cusp, the career requires patience, perseverance, and long-term commitment before recognition arrives. Success comes late but is durable. Careers in government, administration, law, labor, real estate, or research are favored.',
  },
  {
    id: 'car-05',
    section: 'career',
    planets: ['Mars'],
    houses: [10],
    rule: 'If Mars is prominent in the 10th cusp sub-lord significations, careers in engineering, defense, surgery, sports, construction, real estate development, police, or any field requiring physical decisiveness and energy are strongly indicated.',
  },
  {
    id: 'car-06',
    section: 'career',
    planets: ['Mercury'],
    houses: [10],
    rule: 'If Mercury is prominent in the 10th cusp significations, careers in communication, writing, accounting, software, teaching, trading, consulting, or any intellectual or analytical field are indicated.',
  },
  {
    id: 'car-07',
    section: 'career',
    planets: ['Venus'],
    houses: [10],
    rule: 'If Venus is prominent in the 10th cusp significations, careers in arts, beauty, fashion, entertainment, hospitality, diplomacy, luxury goods, or any aesthetically-driven field are favored. The native succeeds where beauty and relatability matter.',
  },
  {
    id: 'car-08',
    section: 'career',
    planets: ['Jupiter'],
    houses: [10],
    rule: 'If Jupiter is the dominant planet in the 10th cusp significations, careers in law, finance, teaching, counseling, philosophy, religious leadership, or any advisory or wisdom-giving role are indicated. The native becomes an authority others seek guidance from.',
  },
  {
    id: 'car-09',
    section: 'career',
    planets: ['Sun'],
    houses: [10],
    rule: 'If Sun is prominent in 10th cusp significations, government service, administration, leadership, politics, or any role requiring authority and public visibility suits the native. The native naturally gravitates toward positions of command.',
  },
  {
    id: 'car-10',
    section: 'career',
    planets: ['Moon'],
    houses: [10],
    rule: 'If Moon is prominent in 10th cusp significations, the native\'s career involves public service, hospitality, food, nursing, travel, counseling, or fields with variable income. Income may fluctuate like the Moon\'s phases but the career has a public-facing quality.',
  },
  {
    id: 'car-11',
    section: 'career',
    planets: ['Rahu'],
    houses: [10],
    rule: 'If Rahu is the sub-lord of the 10th cusp (in the star of a well-placed planet), sudden career elevation is possible, often in unconventional, modern, or foreign-connected fields — technology, media, foreign corporations, research, or mass communication.',
  },
  {
    id: 'car-12',
    section: 'career',
    houses: [10, 12],
    rule: 'If the 10th cusp sub-lord signifies house 12 along with 10, the career involves foreign companies, research institutions, hospitals, prisons, remote work, spiritual organizations, or behind-the-scenes creative work.',
  },
  {
    id: 'car-13',
    section: 'career',
    keywords: ['promotion', 'timing', 'dasha'],
    rule: 'Promotion or salary raise timing in KP: the dasha of a planet that simultaneously signifies houses 6, 10, and 11 — and when the current Mahadasha lord also signifies at least two of these houses. Both dasha levels must align.',
  },
  {
    id: 'car-14',
    section: 'career',
    keywords: ['business', 'timing', 'dasha'],
    rule: 'Business success and profit timing: the dasha of a planet signifying houses 2, 7, 10, and 11 simultaneously. The rarer this combination, the more significant the business milestone — it marks a period of exceptional commercial opportunity.',
  },
  {
    id: 'car-15',
    section: 'career',
    keywords: ['career change', 'multiple careers'],
    rule: 'If the 10th cusp sub-lord is in the star of a retrograde planet, the native changes careers multiple times, faces significant setbacks before finding direction, or achieves recognition only after reversals. The career path is non-linear.',
  },
  {
    id: 'car-16',
    section: 'career',
    houses: [10, 6],
    keywords: ['government'],
    rule: 'Government employment specifically requires the Sun to be a significator of houses 6 and 10. The combination of the Sun\'s natural authority with service (6th) and career (10th) is the classic government-job combination in KP.',
  },
  {
    id: 'car-17',
    section: 'career',
    keywords: ['self-employment', 'freelance'],
    rule: 'Self-employment or freelance work (as distinct from business with partners) is indicated when the 10th cusp sub-lord signifies houses 1, 3, 10, and 11 without strong 6th house connection. The native works independently, outside formal employment structures.',
  },
  {
    id: 'car-18',
    section: 'career',
    keywords: ['foreign', 'abroad', 'international'],
    rule: 'A career abroad or with an international dimension is strongly indicated when the 10th cusp sub-lord signifies houses 9 or 12 along with 10, and the 12th cusp sub-lord is in a constellation that supports overseas enterprise.',
  },
  {
    id: 'car-19',
    section: 'career',
    planets: ['Saturn'],
    keywords: ['transit', 'gochar'],
    rule: 'Saturn\'s transit over the natal 10th cusp degree or the natal position of the 10th cusp sub-lord marks a critical career pressure point — a time of either forced restructuring or (if the chart promises success) consolidation of significant professional achievement.',
  },
  {
    id: 'car-20',
    section: 'career',
    keywords: ['denial', 'obstruction'],
    rule: 'Career obstruction or professional plateau is indicated when the current Mahadasha planet primarily signifies houses 1, 4, 8, or 12 without connecting to 6, 10, or 11. In such periods, the native is advised to consolidate rather than push for advancement.',
  },
];
