import type { KPRule } from '../types';

export const wealth: KPRule[] = [
  {
    id: 'wlth-01',
    section: 'wealth',
    houses: [11],
    rule: 'The 11th cusp sub-lord is the primary indicator of financial gains in KP. If it signifies houses 2 and 11, steady accumulation is promised. If it primarily signifies 6, 8, or 12, financial gains are erratic, delayed, or consistently drained.',
  },
  {
    id: 'wlth-02',
    section: 'wealth',
    houses: [2],
    rule: 'The 2nd cusp sub-lord reveals the primary source of income and the capacity for savings. Connection with house 10 or 6 indicates earned income; with house 8 indicates legacies or inheritance; with house 5 points to speculation or creative earnings; with house 1 or 9 indicates self-made fortune.',
  },
  {
    id: 'wlth-03',
    section: 'wealth',
    houses: [2, 6, 10, 11],
    keywords: ['dhana yoga', 'wealth combination'],
    rule: 'The KP Dhana Yoga (wealth combination): when the significators of houses 2, 6, 10, and 11 are simultaneously active in the current dasha, significant wealth accumulation is possible. The more houses in this set that are signified by the dasha planets, the stronger the financial potential in that period.',
  },
  {
    id: 'wlth-04',
    section: 'wealth',
    houses: [8, 11],
    keywords: ['inheritance', 'legacy'],
    rule: 'Inheritance, insurance proceeds, or unexpected windfall is indicated when the 8th cusp sub-lord signifies houses 2 and 11, and the 8th house significators are active in the dasha. The 8th house in KP is positive for receiving others\' money.',
  },
  {
    id: 'wlth-05',
    section: 'wealth',
    houses: [8, 11],
    keywords: ['windfall', 'sudden gain', 'lottery'],
    rule: 'Sudden or unexpected financial gains (windfalls, lottery, large bonuses) require both the 8th and 11th cusps to promise gains. The dasha must be of significators of houses 8 and 11 simultaneously — this combination is rare and marks an exceptional financial event.',
  },
  {
    id: 'wlth-06',
    section: 'wealth',
    houses: [6, 8, 12],
    keywords: ['financial loss', 'debt'],
    rule: 'A period of financial loss or heavy expenditure is indicated when the current dasha lord primarily signifies houses 6, 8, or 12 without compensating 2/11 connections. House 6 = debt; house 8 = sudden financial disruption; house 12 = spending exceeds earnings.',
  },
  {
    id: 'wlth-07',
    section: 'wealth',
    houses: [4, 11, 12],
    keywords: ['property', 'real estate'],
    rule: 'Real estate wealth is indicated when the 4th cusp sub-lord signifies houses 4 (property), 11 (gains), and 12 (expenditure for acquisition — buying uses savings). The 12th house connection here is positive: it shows money going out to purchase an asset.',
  },
  {
    id: 'wlth-08',
    section: 'wealth',
    houses: [5, 2, 11],
    keywords: ['speculation', 'investment', 'profit'],
    rule: 'Profitable speculation and investment returns are indicated when the 5th cusp sub-lord signifies houses 2, 5, and 11 — risk (5th) leading to accumulation (2nd) and gain (11th). If house 8 or 12 dominates instead, speculation leads to loss.',
  },
  {
    id: 'wlth-09',
    section: 'wealth',
    planets: ['Jupiter'],
    keywords: ['wealth', 'expansion'],
    rule: 'Jupiter as a significator of houses 2, 9, and 11 gives a natural tendency toward growing wealth over time. Jupiter expands what it touches — when it signifies the wealth houses, accumulated savings and investments tend to grow through wise decision-making.',
  },
  {
    id: 'wlth-10',
    section: 'wealth',
    planets: ['Saturn'],
    keywords: ['wealth', 'discipline'],
    rule: 'Saturn as a significator of houses 2 and 11 indicates that wealth comes slowly, through disciplined long-term effort, and after the age of 36-40. Saturn\'s wealth, once built, is lasting and conservative.',
  },
  {
    id: 'wlth-11',
    section: 'wealth',
    planets: ['Rahu'],
    keywords: ['sudden wealth', 'unconventional'],
    rule: 'Rahu as a significator of houses 2 and 11 (in the star of a planet occupying or ruling those houses) can bring sudden and disproportionate financial gains — often through unconventional means, foreign income, technology, or speculation. The gains are real but may come with unpredictability.',
  },
  {
    id: 'wlth-12',
    section: 'wealth',
    keywords: ['timing', 'accumulation peak'],
    rule: 'The peak wealth accumulation period occurs when: the Mahadasha lord signifies 2, 10, and 11; the Antardasha lord also signifies at least two of 2/10/11; and Jupiter simultaneously transits a position favorable to the natal Moon or the 2nd/11th cusp. All three must converge.',
  },
  {
    id: 'wlth-13',
    section: 'wealth',
    houses: [9, 10, 11],
    keywords: ['lakshmi yoga'],
    rule: 'Lakshmi Yoga in KP: when the 9th cusp sub-lord (fortune) and the 11th cusp sub-lord (gains) both signify houses associated with the 10th (career), the native earns significant wealth through dharmic or professional pursuits. This is a blessed financial pattern.',
  },
  {
    id: 'wlth-14',
    section: 'wealth',
    houses: [2, 7, 11],
    keywords: ['business wealth', 'partnership'],
    rule: 'Wealth through business partnerships is indicated when the 7th cusp sub-lord (partnerships) and the 11th cusp sub-lord (gains) both signify houses 2 and 11. The native profits specifically from joint ventures and client relationships.',
  },
  {
    id: 'wlth-15',
    section: 'wealth',
    keywords: ['financial timing', 'dasha'],
    rule: 'In a Mahadasha that is fundamentally unfavorable for wealth (its planet primarily signifies 6/8/12 without 2/11), no Antardasha, however favorable, can produce lasting financial gains — only temporary relief. The Mahadasha sets the ceiling.',
  },
];
