import type { KPRule } from '../types';

export const health: KPRule[] = [
  {
    id: 'hlth-01',
    section: 'health',
    houses: [1],
    rule: 'The 1st cusp sub-lord is the primary indicator of physical constitution and overall vitality in KP. It defines the baseline health pattern for the entire life and determines susceptibility to illness.',
  },
  {
    id: 'hlth-02',
    section: 'health',
    houses: [1, 5, 9],
    rule: 'If the 1st cusp sub-lord primarily signifies trine houses (1, 5, 9) without significant 6/8/12 connection, the native has robust natural vitality. Health challenges exist for everyone, but this native recovers swiftly and maintains energy through most of life.',
  },
  {
    id: 'hlth-03',
    section: 'health',
    houses: [1, 6],
    rule: 'If the 1st cusp sub-lord signifies house 6, the native is susceptible to recurring but manageable illness. The 6th house describes the nature of recurring ailments. The native functions in a "service under pressure" health pattern — often burning the candle at both ends.',
  },
  {
    id: 'hlth-04',
    section: 'health',
    houses: [1, 8],
    rule: 'If the 1st cusp sub-lord primarily signifies house 8, chronic, serious, or transformative illness is indicated. Surgery is possible (Mars signifying 1 and 8 specifically). The native may experience life-altering health events that fundamentally reshape their relationship with their body.',
  },
  {
    id: 'hlth-05',
    section: 'health',
    houses: [1, 12],
    rule: 'If the 1st cusp sub-lord primarily signifies house 12, the native is sensitive to hidden or psychosomatic conditions, hospitalization, or mental health challenges. Sleep difficulties, reclusive periods during illness, and heightened emotional sensitivity to physical symptoms are common.',
  },
  {
    id: 'hlth-06',
    section: 'health',
    houses: [1, 6, 8, 12],
    keywords: ['acute illness', 'timing'],
    rule: 'Acute illness timing: the dasha of a planet that simultaneously signifies houses 6, 8, or 12 — especially when that planet\'s dasha is also triggered by a transit over the natal Lagna cusp degree. The combination of dasha activation and transit confirmation marks the illness window.',
  },
  {
    id: 'hlth-07',
    section: 'health',
    planets: ['Mars'],
    houses: [1, 8, 12],
    keywords: ['surgery'],
    rule: 'Surgery is specifically indicated when Mars is a significator of houses 1, 8, and 12 simultaneously, AND the current dasha has Mars active. The 1st house connection ensures the native\'s body is involved; the 8th is transformation; the 12th is the operating table (bed of a hospital).',
  },
  {
    id: 'hlth-08',
    section: 'health',
    planets: ['Moon', 'Saturn'],
    houses: [8, 12],
    keywords: ['mental health'],
    rule: 'Mental health sensitivity is indicated in KP when Moon is the sub-lord of the 1st cusp and simultaneously signifies houses 8 or 12 through its star lord. Saturn\'s influence on Moon (Moon in Saturn\'s star, or Saturn in Moon\'s star) adds chronic melancholy or anxiety to this pattern.',
  },
  {
    id: 'hlth-09',
    section: 'health',
    houses: [1, 5, 9, 11],
    keywords: ['recovery', 'healing'],
    rule: 'Recovery from illness occurs when the dasha shifts to a planet that primarily signifies houses 1 (self), 5 (creativity, vitality), 9 (fortune), and 11 (gains/recovery). The 11th house in KP represents recovery from illness — the fulfillment of the desire to be well.',
  },
  {
    id: 'hlth-10',
    section: 'health',
    houses: [1, 3, 8],
    keywords: ['longevity'],
    rule: 'Longevity is well-supported when the 8th cusp sub-lord primarily signifies houses 1 and 3 without strong maraka (2nd and 7th) connection. Houses 1 and 3 are life-affirming; the 3rd is the 8th from the 8th (longevity of longevity).',
  },
  {
    id: 'hlth-11',
    section: 'health',
    planets: ['Saturn'],
    keywords: ['chronic', 'degeneration'],
    rule: 'Chronic or degenerative conditions are more likely when Saturn is a significator of houses 1 and 6 in the KP cascade, particularly if Saturn also rules the 6th house or occupies it. Saturn\'s nature is slow accumulation — chronic conditions build gradually over years.',
  },
  {
    id: 'hlth-12',
    section: 'health',
    planets: ['Rahu', 'Ketu'],
    keywords: ['mysterious illness', 'misdiagnosis'],
    rule: 'Mysterious, difficult-to-diagnose, or psychosomatic illness is indicated when Rahu or Ketu are the sub-lord of the 1st cusp or are significators of the 6th and 12th houses in the dasha period. Medical tests may be inconclusive; the condition may have a strong mental-emotional component.',
  },
  {
    id: 'hlth-13',
    section: 'health',
    keywords: ['preventive', 'protective'],
    rule: 'The most important protective health factor in a chart is when the 1st cusp sub-lord signifies a house ruled by Jupiter (9th or 12th in Sagittarius/Pisces charts) or when Jupiter is a strong significator of the 1st house. Jupiter\'s healing energy gives natural resilience.',
  },
  {
    id: 'hlth-14',
    section: 'health',
    planets: ['Saturn'],
    keywords: ['sade sati', 'health'],
    rule: 'During Saturn\'s Sade Sati (7.5-year transit through the sign before, the sign of, and the sign after the natal Moon), health requires extra vigilance — particularly in the middle phase when Saturn transits the natal Moon\'s sign. This is a period of maximum physical and emotional pressure.',
  },
  {
    id: 'hlth-15',
    section: 'health',
    keywords: ['body part', 'organ system'],
    rule: 'The body part or organ system most likely to be affected during illness is indicated by the sign occupied by the 6th cusp and the nature of the planets signifying the 6th house. Aries/Mars = head; Taurus/Venus = throat; Gemini/Mercury = lungs and nerves; Cancer/Moon = stomach; Leo/Sun = heart; Virgo/Mercury = intestines; Libra/Venus = kidneys; Scorpio/Mars = reproductive system; Sagittarius/Jupiter = liver and hips; Capricorn/Saturn = knees and joints; Aquarius/Saturn = ankles and circulation; Pisces/Jupiter = feet and lymphatic system.',
  },
];
