import type { PlanetId } from '@luckyray/shared';

// ─── Birth Time Window ────────────────────────────────────────────────────────

export interface TimeWindow {
  birthDate: string;        // "YYYY-MM-DD"
  centerTime: string | null; // "HH:MM" if user has an approximate, null if unknown
  windowMinutes: number;    // ± half-width of uncertainty (null = 720, i.e. full day)
  latitude: number;
  longitude: number;
  timezone: string;
  utcOffset: number;
}

// ─── Candidate Birth Time ─────────────────────────────────────────────────────

export interface CandidateBirthTime {
  time: string;                // "HH:MM"
  probability: number;         // 0–1, sums to 1 across all candidates
  ascendantSign: string;       // e.g. "Libra"
  ascendantDegrees: number;    // 0–360
  ascendantSubLord: string;    // KP sub-lord of Ascendant cusp
  moonSiderealLon: number;     // precomputed to seed dasha
  dashaData?: CompactDashaMap; // year → {md, ad}
}

/** Compact year-keyed dasha state for discrimination. Year is "YYYY". */
export type CompactDashaMap = Record<string, { md: PlanetId; ad: PlanetId | null }>;

// ─── Evidence System ──────────────────────────────────────────────────────────

export type EvidenceType = 'physical' | 'voice' | 'personality' | 'interview' | 'ruling-planets';

export interface EvidenceEntry {
  type: EvidenceType;
  description: string;         // human-readable summary
  planetLikelihoods?: Partial<Record<string, number>>; // rising sign → likelihood multiplier
  /** For interview evidence: which candidates were affected */
  candidateScores?: Record<string, number>; // candidate time → score delta
  appliedAt: string;           // ISO timestamp
}

// ─── Interview System ─────────────────────────────────────────────────────────

/** A question generated by the discriminator. */
export interface GeneratedQuestion {
  id: string;
  yearStart: number;
  yearEnd: number;
  /** The two (or more) planet groups the candidates split into */
  groups: QuestionGroup[];
  /** Framed question text shown to the user */
  questionText: string;
  /** Brief instruction hint */
  hint: string;
}

export interface QuestionGroup {
  planets: PlanetId[];           // MD + AD planets forming this group
  themeLabel: string;            // e.g. "discipline, restriction, career consolidation"
  candidateCount: number;        // how many candidates are in this group
  candidateTimes: string[];      // "HH:MM" keys
}

/** User's answer to an interview question. */
export interface InterviewAnswer {
  questionId: string;
  freeText: string;              // user's open description
  selectedThemes?: string[];     // if user picks from presented themes
}

/** AI scoring result for an answer */
export interface AnswerScoringResult {
  questionId: string;
  bestMatchGroup: number;        // index into GeneratedQuestion.groups
  confidence: number;            // 0–1
  reasoning: string;             // 1-sentence explanation
  candidateScores: Record<string, number>; // time → multiplier (e.g. 2.0 if match, 0.3 if mismatch)
}

// ─── Rising Sign Physical Profiles ───────────────────────────────────────────

export interface SignPhysicalProfile {
  sign: string;
  build: string;
  height: string;
  complexion: string;
  faceShape: string;
  eyeCharacter: string;
  hairTendency: string;
  distinguishingFeature: string;
  voiceQuality: string;
  movementStyle: string;
}

// ─── Journey State (serializable for client) ─────────────────────────────────

export type JourneyStep = 'seed' | 'physical' | 'interview' | 'result';

export interface JourneyState {
  step: JourneyStep;
  profileId: string;
  window: TimeWindow;
  candidates: CandidateBirthTime[];  // all candidates, ordered by probability desc
  evidenceLog: EvidenceEntry[];
  questionsAsked: GeneratedQuestion[];
  answersGiven: InterviewAnswer[];
  scoringResults: AnswerScoringResult[];
  /** Convergence: true when top candidate has ≥ 60% probability */
  hasConverged: boolean;
  /** The final recommended time once converged */
  recommendedTime?: string;
}

// ─── API Payload Types ────────────────────────────────────────────────────────

export interface NextQuestionPayload {
  candidates: CandidateBirthTime[];
  questionsAlreadyAsked: GeneratedQuestion[];
  birthYear: number;
}

export interface NextQuestionResponse {
  question: GeneratedQuestion | null; // null = no more discriminating questions
  remainingCandidateCount: number;
  topCandidates: Array<{ time: string; probability: number; ascendantSign: string }>;
}

export interface ScoreAnswerPayload {
  question: GeneratedQuestion;
  answer: InterviewAnswer;
  planetThemeContext: string; // serialized planet themes for the AI
}

export interface ScoreAnswerResponse {
  result: AnswerScoringResult;
  updatedCandidates: CandidateBirthTime[];
}

export interface AnalyzePhysicalPayload {
  signProfiles: SignPhysicalProfile[];
  userDescriptions: {
    height: string;
    build: string;
    complexion: string;
    faceNotes: string;
    voiceNotes?: string;
    additionalFeatures?: string;
  };
  hasPhoto: boolean;
}

export interface AnalyzePhysicalResponse {
  signLikelihoods: Record<string, number>; // sign → 0–1 score
  eliminatedSigns: string[];
  reasoning: string;
  topSigns: string[];
}
